apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-autorollout.fullname" . }}-config
  labels:
    {{- include "kube-autorollout.labels" . | nindent 4 }}
data:
  config.yaml: |-
    cronSchedule: {{ .Values.config.cronSchedule | quote }}
    webserver:
      port: {{ .Values.config.webserver.port }}
    registries:
    {{- range .Values.config.registries }}
      - hostnamePattern: {{ required "Missing .hostnamePattern for registry" .hostnamePattern | quote }}
      {{- with required (printf "Missing .secret for registry with hostnamePattern %s" .hostnamePattern) .secret }}
        secret:
        {{- $secretType := .type }}
        {{- if not (or (eq $secretType "ImagePullSecret") (eq $secretType "Opaque") (eq $secretType "None")) }}
          {{ fail (printf "Invalid input value for secret type: %s. Must be one of: ImagePullSecret, Opaque, None" $secretType) }}
        {{- end }}
        {{- if eq $secretType "ImagePullSecret" }}
          type: ImagePullSecret
          name: {{ required "A .name entry is required for secret type ImagePullSecret!" .name }}
          mountPath: {{ required "A .mountPath entry is required for secret type ImagePullSecret!" .mountPath }}
        {{- else if eq $secretType "Opaque" }}
          type: Opaque
          username: {{ .username }}
          {{- if .token }}
          token: {{ .token | quote }}
          {{- else if .key }}
          token: {{ printf "${%s}" .key | quote }}
          {{- else }}
          {{ fail "registry secret must contain .token or .key (the latter is preferred)" }}
          {{ end }}
        {{- else if eq $secretType "None" }}
          type: None
        {{- end }}
      {{- end }}
    {{- end }}
    tls:
      caCertificatePaths:
      {{- if .Values.config.tls.customCaCertificates.enabled }}
      {{- range .Values.config.tls.customCaCertificates.secrets }}
        - {{ .mountPath }}
      {{- end }}
      {{- else }}
        []
      {{- end }}
    featureFlags:
      enableJfrogArtifactoryFallback: {{ .Values.config.featureFlags.enableJfrogArtifactoryFallback }}
      enableKubectlAnnotation: {{ .Values.config.featureFlags.enableKubectlAnnotation }}
