name: Publish Crate

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo git
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: git-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache target directory
        uses: actions/cache@v3
        with:
          path: target
          key: build-stable-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Lint with Clippy
        run: cargo clippy --all -- -D warnings

      - name: Run Tests
        run: cargo test --all --locked --verbose

      - name: Dry-run publish
        run: cargo publish --dry-run --locked

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish --locked