name: Helm Publish

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full history for diff

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Check for changes in Helm chart directory
        id: chart_changed
        run: |
          if git diff --quiet origin/${{ github.event.pull_request.base.ref }} -- ./charts/kube-autorollout; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Install Helm
        if: steps.chart_changed.outputs.changed == 'true'
        uses: azure/setup-helm@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm Chart
        if: steps.chart_changed.outputs.changed == 'true'
        run: helm package ./charts/kube-autorollout

      - name: Push Helm Chart to GHCR
        if: steps.chart_changed.outputs.changed == 'true'
        run: |
          CHART_VERSION=$(helm show chart ./charts/kube-autorollout | grep version | awk '{ print $2 }')
          helm push ./kube-autorollout-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
